In [1]:
from torch.utils.data import dataset

In [2]:
help(dataset)

Help on module torch.utils.data.dataset in torch.utils.data:

NAME
    torch.utils.data.dataset

CLASSES
    typing.Generic(builtins.object)
        Dataset
            ConcatDataset
            IterableDataset
                ChainDataset
            Subset
            TensorDataset
    
    class ChainDataset(IterableDataset)
     |  ChainDataset(datasets: Iterable[torch.utils.data.dataset.Dataset]) -> None
     |  
     |  Dataset for chaining multiple :class:`IterableDataset` s.
     |  
     |  This class is useful to assemble different existing dataset streams. The
     |  chaining operation is done on-the-fly, so concatenating large-scale
     |  datasets with this class will be efficient.
     |  
     |  Args:
     |      datasets (iterable of IterableDataset): datasets to be chained together
     |  
     |  Method resolution order:
     |      ChainDataset
     |      IterableDataset
     |      Dataset
     |      typing.Generic
     |      builtins.object
     |  
     |  

In [3]:
from PIL import Image

In [4]:
img_path = "D:\\Python_project\\PNeural_project\\dataset\\train\\ants_image\\0013035.jpg"

In [5]:
img = Image.open(img_path)

In [6]:
img.show()

In [7]:
import os

In [8]:
dir_path = 'dataset/train/ants_image'

In [9]:
img_path_list = os.listdir(dir_path)

In [10]:
img_path_list[2]

'1095476100_3906d8afde.jpg'

In [11]:
root_dir = "dataset/train"
label_dir = "ants_image"

In [12]:
path = os.path.join(root_dir, label_dir)

In [13]:
print(path)

dataset/train\ants_image


In [14]:
img_path = os.listdir(path)

In [15]:
print(img_path)

['0013035.jpg', '1030023514_aad5c608f9.jpg', '1095476100_3906d8afde.jpg', '1099452230_d1949d3250.jpg', '116570827_e9c126745d.jpg', '1225872729_6f0856588f.jpg', '1262877379_64fcada201.jpg', '1269756697_0bce92cdab.jpg', '1286984635_5119e80de1.jpg', '132478121_2a430adea2.jpg', '1360291657_dc248c5eea.jpg', '1368913450_e146e2fb6d.jpg', '1473187633_63ccaacea6.jpg', '148715752_302c84f5a4.jpg', '1489674356_09d48dde0a.jpg', '149244013_c529578289.jpg', '150801003_3390b73135.jpg', '150801171_cd86f17ed8.jpg', '154124431_65460430f2.jpg', '162603798_40b51f1654.jpg', '1660097129_384bf54490.jpg', '167890289_dd5ba923f3.jpg', '1693954099_46d4c20605.jpg', '175998972.jpg', '178538489_bec7649292.jpg', '1804095607_0341701e1c.jpg', '1808777855_2a895621d7.jpg', '188552436_605cc9b36b.jpg', '1917341202_d00a7f9af5.jpg', '1924473702_daa9aacdbe.jpg', '196057951_63bf063b92.jpg', '196757565_326437f5fe.jpg', '201558278_fe4caecc76.jpg', '201790779_527f4c0168.jpg', '2019439677_2db655d361.jpg', '207947948_3ab29d7207.jpg

In [16]:
idx = 0

In [17]:
img_item_path = os.path.join(root_dir,label_dir,img_path[idx])

In [18]:
print(img_item_path)

dataset/train\ants_image\0013035.jpg


In [19]:
img2 = Image.open(img_item_path)

In [20]:
img2.show()

In [21]:
from torch.utils.data import Dataset
from PIL import Image
import os

class Mydata(Dataset):

    def __init__(self, root_dir, label_dir):
        self.root_dir = root_dir
        self.label_dir = label_dir
        self.path = os.path.join(self.root_dir, self.label_dir)
        self.img_path = os.listdir(self.path)

    def __getitem__(self, idx):
        img_name = self.img_path[idx]
        img_item_path = os.path.join(self.root_dir, self.label_dir, img_name)
        img = Image.open(img_item_path)
        label = self.label_dir
        return img, label

    def __len__(self):
        return len(self.img_path)


In [22]:
root_dir = "dataset/train"
ants_label_dir = "ants_image"
bees_label_dir = "bees_image"

In [23]:
ants_dataset = Mydata(root_dir, ants_label_dir)

In [24]:
ants_dataset = Mydata(root_dir, ants_label_dir)
bees_dataset = Mydata(root_dir, bees_label_dir)

In [25]:
img1, label1 = ants_dataset[1]

In [26]:
img1.show()

In [27]:
print(label1)

ants_image


In [28]:
img2, label2 = bees_dataset[1]

In [29]:
img2.show()

In [30]:
print(label2)

bees_image


In [31]:
train_dataset = ants_dataset + bees_dataset

In [32]:
len(train_dataset)

245

In [33]:
len(ants_dataset)

124

In [34]:
len(bees_dataset)

121

In [35]:
img3, label3 = train_dataset[123]

In [36]:
img3.show()

In [37]:
img4, label4 = train_dataset[124]

In [38]:
img4.show()

In [42]:
from torch.utils.tensorboard import SummaryWriter

In [43]:
writer = SummaryWriter("logs")

# writer.add_image()

# y = x
for i in range(100):
    writer.add_scalar('y=3x',3*i , i)
# writer.add_scalar()

writer.close()


tensorboard --logdir=logs #RUN IN TERMINAL

In [45]:
from PIL import Image
import numpy as np

In [47]:
img = Image.open('dataset/train/ants_image/0013035.jpg')

In [48]:
print(type(img))

<class 'PIL.JpegImagePlugin.JpegImageFile'>


In [50]:
img_array = np.array(img)

In [51]:
print(type(img_array))

<class 'numpy.ndarray'>


In [52]:
print(img_array)

[[[ 80 151 233]
  [ 80 151 233]
  [ 80 151 233]
  ...
  [ 81 152 234]
  [ 79 150 232]
  [ 76 147 229]]

 [[ 81 152 234]
  [ 81 152 234]
  [ 81 152 234]
  ...
  [ 81 152 234]
  [ 79 150 232]
  [ 76 147 229]]

 [[ 82 153 235]
  [ 82 153 235]
  [ 82 153 235]
  ...
  [ 80 151 233]
  [ 79 150 232]
  [ 77 148 230]]

 ...

 [[ 87 160 237]
  [ 87 160 237]
  [ 86 159 236]
  ...
  [ 44  92 141]
  [ 95 158 235]
  [ 90 157 228]]

 [[ 87 160 237]
  [ 87 160 237]
  [ 86 159 236]
  ...
  [ 84 147 226]
  [ 90 160 255]
  [ 84 152 233]]

 [[ 87 160 237]
  [ 87 160 237]
  [ 86 159 236]
  ...
  [ 79 160 242]
  [ 78 159 250]
  [ 84 161 233]]]


In [53]:
from torch.utils.tensorboard import SummaryWriter
from PIL import Image
import numpy as np

writer = SummaryWriter("logs")
img_path = 'dataset/train/bees_image/16838648_415acd9e3f.jpg'
img_PIL = Image.open(img_path)
img_array = np.array(img_PIL)
print(img_array.shape)

writer.add_image('test', img_array, 2, dataformats='HWC')


writer.close()

(450, 500, 3)


In [1]:
from torchvision import transforms
from PIL import Image
import numpy as np

# Usage of Python --> Totensor data type
# From transform.Totensor，解决两个问题
# 2， Tensor 数据类型的特点，以及为什么需要这个类型的数据。


img_path = 'D:\\Python_project\\PNeural_project\\dataset\\train\\ants_image\\0013035.jpg'
# 1. Transform 的使用方法；
img = Image.open(img_path)
tensor_trans = transforms.ToTensor()        # 函数重定向声明
tensor_img = tensor_trans(img)
print(tensor_img)

tensor([[[0.3137, 0.3137, 0.3137,  ..., 0.3176, 0.3098, 0.2980],
         [0.3176, 0.3176, 0.3176,  ..., 0.3176, 0.3098, 0.2980],
         [0.3216, 0.3216, 0.3216,  ..., 0.3137, 0.3098, 0.3020],
         ...,
         [0.3412, 0.3412, 0.3373,  ..., 0.1725, 0.3725, 0.3529],
         [0.3412, 0.3412, 0.3373,  ..., 0.3294, 0.3529, 0.3294],
         [0.3412, 0.3412, 0.3373,  ..., 0.3098, 0.3059, 0.3294]],

        [[0.5922, 0.5922, 0.5922,  ..., 0.5961, 0.5882, 0.5765],
         [0.5961, 0.5961, 0.5961,  ..., 0.5961, 0.5882, 0.5765],
         [0.6000, 0.6000, 0.6000,  ..., 0.5922, 0.5882, 0.5804],
         ...,
         [0.6275, 0.6275, 0.6235,  ..., 0.3608, 0.6196, 0.6157],
         [0.6275, 0.6275, 0.6235,  ..., 0.5765, 0.6275, 0.5961],
         [0.6275, 0.6275, 0.6235,  ..., 0.6275, 0.6235, 0.6314]],

        [[0.9137, 0.9137, 0.9137,  ..., 0.9176, 0.9098, 0.8980],
         [0.9176, 0.9176, 0.9176,  ..., 0.9176, 0.9098, 0.8980],
         [0.9216, 0.9216, 0.9216,  ..., 0.9137, 0.9098, 0.

In [2]:
import cv2

In [3]:
cv_img = cv2.imread(img_path)

In [4]:
print(type(cv_img))

<class 'numpy.ndarray'>


可以看到 TOTENSOR 输入的数据类型同时支持 CV2 和 PIL 读入。